[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cic"
version = "1.0"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = ["pexpect", "sshkeyboard", "flask-restx"]

[project.optional-dependencies]

[tool.setuptools]
packages = ["cic"]
