[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "merely_players"
version = "1.0"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = ["pexpect==4.9.0", "sshkeyboard==2.3.1", "fastapi[standard]==0.121.0"]

[project.optional-dependencies]
